### PR TITLE
fix(parser): fix parsing merged numbers with arc flags

### PR DESCRIPTION
**Pull request by nfroidure**
Linked to: https://github.com/nfroidure/svg-pathdata/issues/36

### CODE REVIEW

**Comment by NaridaL** [comment]
@nfroidure heads up, I added more tests from https://github.com/nfroidure/svg-pathdata/issues/36#issuecomment-580238472 and I rebased it onto master.

**Comment by nfroidure** [comment]
@NaridaL thanks, fixed the parser for those too.

**Comment by pioug** [comment]
Awesome 🙌 May I go ahead and release an update of the package?

**Comment by nfroidure** [comment]
@pioug of course, feel free to, you have npm/gh if I remind well but feel free to ask anything if needed.

**Comment by pioug** [comment]
@nfroidure Apparently I don't have the permission to publish the npm package. Anyway, we just need to run `npm publish` now 🤞

**Pull request merged**
