### PR TITLE
Fix ESM support

### PR DESCRIPTION
**Pull request by alecmev**
### Proposed changes

If you try running code that name-imports `svg-pathdata` using something like `node --loader ts-node/esm foo.ts`, you would get the following error:

```bash
import { SVGPathData } from 'svg-pathdata';
         ^^^^^^^^^^^
SyntaxError: Named export 'SVGPathData' not found. The requested module 'svg-pathdata' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'svg-pathdata';
const { SVGPathData } = pkg;
```

This PR fixes this. I'm no module/bundler specialist though, so I don't know what to test, so have no idea if this is going to break anything for anybody. `"type": "module"` certainly has the explosive potential.

[Node's ESM docs](https://nodejs.org/docs/latest-v14.x/api/esm.html).

### Code quality

- [ ] I made some tests for my changes
- [ ] I added my name in the
 [contributors](https://docs.npmjs.com/files/package.json#people-fields-author-contributors)
 field of the package.json file

### License

To get your contribution merged, you must check the following.

- [x] I read the project license in the LICENSE file
- [x] I agree with publishing under this project license

### CODE REVIEW

**Comment by pioug** [comment]
Did a quick test and it seems like `"type": "module"` can break existing projects.

```
$ node test.js 
/Users/piou/Dev/svgest/test.js:1
const { SVGPathData } = require('svg-pathdata');
                        ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/piou/Dev/svg-pathdata/lib/SVGPathData.js from /Users/piou/Dev/svgest/test.js not supported.
SVGPathData.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename SVGPathData.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/piou/Dev/svg-pathdata/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

I think using `.cjs` would be good enough. By changing `lib/SVGPathData.js` to `lib/SVGPathData.cjs`, we will do something similar to the example in https://nodejs.org/api/packages.html#packages_approach_2_isolate_state

**Comment by alecmev** [comment]
Thank you for looking into this! Would you like me to make that change?

**Comment by pioug** [comment]
I think so, especially if you want the attribution. I can't seem to modify your PR. You can take this commit https://github.com/nfroidure/svg-pathdata/commit/b65b57d53d413a5493b0e396c1b914b77881182b. Or I can push directly and close the PR. Up to you!

**Comment by alecmev** [comment]
> I can push directly to the main branch and close the PR

This is okay for me, no need to attribute :wink: Thank you!

**Comment by MaikuMori** [comment]
This didn't fix it. I guess the `index.d.ts` is messing things up. Why is that file even needed in a TypeScript project?

**Pull request merged**
